### ISSUE TITLE
ONLY variable does not search extra package path

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#4]
Adding dgcode_val in `DGCODE_EXTRA_PKG_PATH` does not enable to dgcode_val/Examples packages if I do:
```
dgbuild ONLY='Framework::*,Examples/*'
```

**Comment by MilanKlausz** [comment]
There was an issue with the package enabling when handling relative path patterns (such as 'Examples/*') in ALL the pkg search path directories, not just the extra pkg path:
An additional '/*' was added, resulting in regex patterns such as 'dgcode_val/*/Examples/*'  instead of the 'dgcode_val/Examples/*'.
